# Generated by Django 2.2.10 on 2020-11-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('definition', models.CharField(blank=True, max_length=1000, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=1000, null=True)),
                ('examples', models.CharField(blank=True, max_length=1000, null=True)),
                ('type_of', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_meaningful', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('words', models.ManyToManyField(blank=True, related_name='chatids', to='main.Word')),
            ],
        ),
    ]
